### ISSUE TITLE
按了开发板的按键以后微信就连不上去了

### ISSUE THREAD

**Issue by fanghuaqi** [Sensoro/IOT#1]
按了板子上按键就连不上去，请问如何解决？

**Comment by fanghuaqi** [comment]
没有人回答下问题么

**Comment by huiter-zz** [comment]
断下电，重新插拔下上面的小蓝牙模块，然后再接电就可以了。

**Comment by fanghuaqi** [comment]
插拔N次没有用啊，有没有其他测试方法，接串口可以调试之类的？

**Comment by huiter-zz** [comment]
是设备可以连接上，但是不响应命令？
还是连接不上？

**Comment by fanghuaqi** [comment]
点击绑定后，出现连接和解绑，但是点击连接连接不上去，刚拿到板子的时候可以连接上去还可以控制，但是现在就连不上了，而且用手机蓝牙可以找到SensorTag这个设备，应该是微信和板子之间通讯出现异常吧
按了Key1以后输出如下信息
start
all character:                                 rec cmd: 

按了Key2无反应，也无输出

**Comment by fanghuaqi** [comment]
手机是Android 4.4.4,V5 MAX,之前用苹果手机也测试过，也连不上去

**Comment by Davis4Create** [comment]
@fanghuaqi 你好，我现在遇到了同样的问题，请问你解决了吗？是怎么解决的？
