### ISSUE TITLE
板子连上微信后为什么操作了没反应？

### ISSUE THREAD

**Issue by Davis4Create** [Sensoro/IOT#3]
板子刚买来的时候测试了下是可以用的，能够用公众号上的指令操作板子，控制RGB灯开关、电机转动等。后来下了你们github上的代码测试了下，电机例子和温湿度检测例子是可以用的，但是RGB例子无效。现在是想再用微信控制板子，在arduino IDE里上传wechat_hardware.ino固件后，微信还是能连上板子，但是操作指令变得无效了，操控之后板子没有任何反应。这是什么问题呢？是上传的固件文件不对吗？还是固件本身有问题呢？

PS：我没有改过任何东西哦，全部是用你们提供的代码

**Comment by lockeniu** [comment]
用wechat试试。不要用wechat_v2。
